### ISSUE TITLE
Please release to central repository

### ISSUE THREAD

**Issue by scravy** [dwijnand/semver4j#1]
This library looks exactly like what I am looking for but unfortunately it does not seem to be available form the central repository (as a non-snapshot dependency). I can not use it as a dependency in any real project on nexus then :-(

**Comment by dwijnand** [comment]
I haven't looked at this code in a long time. If you don't want to package this yourself, you should consider using JitPack: https://jitpack.io/

**Comment by scravy** [comment]
I care about this thing being released to the central repository such that developers can just plug it into their dependencies.

It looks like it is almost completely configured for releasing it to the central repository (a snapshot is already in sonatype I figure?). If you do not care about it and others may release it for you it would be great if you could add license information, so that it can be done properly.
